### ISSUE TITLE
HOW TO REPLICATE PROJECT TO LARAVEL 5.3 and angular-cli

### ISSUE THREAD

**Issue by chojuanillo** [nilsenj/larang#1]
hello. good job!. 
I have a project in laravel 5.3 and another project in angular-cli, angular 4. What changes should I make to integrate it as this project?

**Comment by nilsenj** [comment]
changes? I think that the only problem you'll have is Laravel update and that's it))
Oh And Yes! I dropped from the package json all vue.js packages and mix plugin!
Also I deleted all the scripts laravel ships out of the box! I deleted resources/assets!
Maybe something else((
Just test it and compare with this project and yours!
Hope It helps
